runtime: nodejs22 

env: standard

instance_class: F1

handlers:
  - url: /api/.*
    script: auto

  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  NODE_ENV: 'production'